name: Build Container

on: push

jobs:
  release-linux-amd64:
    name: Generate Release
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repository
      uses: actions/checkout@master

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.14'

    - name: Verify Go version
      run: go version

    - name: Build Andromedad
      run: GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build ./cmd/andromedad

    - name: Build container
      run: docker build -t ractf/andromeda -t ghcr.io/ractf/andromeda:latest .

    - name: Login to Docker Hub
      if: github.ref == 'refs/heads/master'
      run: docker login --username ractf --password ${{ secrets.password }}

    - name: Login to Github Container Registry
      if: github.ref == 'refs/heads/master'
      run: echo ${{ secrets.ghtoken }} | docker login ghcr.io -u ${{ secrets.ghuser }} --password-stdin

    - name: Push to Docker Hub
      if: github.ref == 'refs/heads/master'
      run: docker push ractf/andromeda:latest

    - name: Push to Github Container Registry
      if: github.ref == 'refs/heads/master'
      run: docker push ghcr.io/ractf/andromeda:latest
